career and career detail done
sampangeran/Website pull request #11
Opened 2022-07-30 13:34 UTC by patriciasky17

2022-08-05 09:36 UTC, sampangeran requested changes
Please migrate owl.js to bootstrap

2022-08-07 15:26 UTC, patriciasky17 commented
Done, 
Summary :
1. I've added the Awards page 
2. Migrate Carousel in Career Page from Owl to Bootstrap
3. Add Filter in Courses Page*

* = this one has bug where the load more function can't be implemented cause I use isotope, might fix this soon.

P.s. still working on the sort function for Courses and Tutors page, but before I continue, please check it first, thank you :D

2022-08-14 15:34 UTC, sampangeran reviewed
Please remove unused assets files (owl js, wow js, etc)

2022-08-15 12:40 UTC, sampangeran approved these changes

2022-08-15 12:40 UTC, merged